apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: my-api
          image: us-central1-docker.pkg.dev/civic-nation-450611-j2/mydotnetrepo/myapiproject:latest
          ports:
            - containerPort: 8080  # ✅ Keep this port for container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-second-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-second-api
  template:
    metadata:
      labels:
        app: my-second-api
    spec:
      containers:
        - name: my-second-api
          image: us-central1-docker.pkg.dev/civic-nation-450611-j2/mydotnetrepo/mysecondapiproject:latest
          ports:
            - containerPort: 9090
              protocol: TCP
          resources: 
            limits:
              ephemeral-storage: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
              ephemeral-storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  type: ClusterIP  # ✅ Change from LoadBalancer to ClusterIP
  selector:
    app: my-api
  ports:
    - protocol: TCP
      port: 80        # ✅ Exposed to Ingress
      targetPort: 8080  # ✅ Matches containerPort
---
apiVersion: v1
kind: Service
metadata:
  name: my-second-api-service
spec:
  type: ClusterIP  # ✅ Change from LoadBalancer to ClusterIP
  selector:
    app: my-second-api
  ports:
    - protocol: TCP
      port: 80        # ✅ Exposed to Ingress
      targetPort: 9090  # ✅ Matches containerPort
