apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: my-api
          image: us-central1-docker.pkg.dev/civic-nation-450611-j2/mydotnetrepo/myapiproject:latest
          ports:
            - containerPort: 80  # ✅ Keep it at 80 for proper routing
---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  type: ClusterIP  # ✅ Changed from NodePort to ClusterIP
  selector:
    app: my-api
  ports:
    - port: 80
      targetPort: 80
