apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mydomain.com
    secretName: my-tls-secret  # ✅ Use the created TLS secret
  rules:
  - host: mydomain.com
    http:
      paths:
      - path: /api1
        pathType: Prefix
        backend:
          service:
            name: my-api-service
            port:
              number: 80
      - path: /api2
        pathType: Prefix
        backend:
          service:
            name: my-second-api-service
            port:
              number: 80
