apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default  # Change if needed
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /weatherforecast
        pathType: Prefix
        backend:
          service:
            name: my-api-service  # First service
            port:
              number: 8080  # Correct port based on your service

      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: my-second-api-service  # Second service
            port:
              number: 9090  # Correct port based on your service
