apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # GKE-specific annotation
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /   # Routes to my-api
        pathType: Prefix
        backend:
          service:
            name: my-api-service
            port:
              number: 80
      - path: /      # Fix for my-second-api
        pathType: Prefix
        backend:
          service:
            name: my-second-api-service
            port:
              number: 80
