apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    # External Load Balancer  
    kubernetes.io/ingress.class: "gce"  
spec:                             
  rules:
    - http:
        paths:           
          - path: /api1
            pathType: Prefix
            backend:
              service:
                name: my-api-service
                port: 
                  number: 80                        
